### ISSUE TITLE
KeyError: 'ADD3'

### ISSUE THREAD

**Issue by ritianjiang** [hyhRise/P-SSN#1]
Hi,

When running construct_reference_network.py on 14_samples_data.txt, there exists error:

Traceback (most recent call last):
  File "construct_reference_network.py", line 105, in <module>
    tumor_gene_array=data[genes[p]]
KeyError: 'ADD3'

**Comment by hyhRise** [comment]
> Hi,
> 
> When running construct_reference_network.py on 14_samples_data.txt, there exists error:
> 
> Traceback (most recent call last):
> File "construct_reference_network.py", line 105, in
> tumor_gene_array=data[genes[p]]
> KeyError: 'ADD3'

two solutions：
1.“reference_network.txt”has been updated in GitHub，you can run “construct_reference_network.py”again；
2. you can use the result of "construct_reference_network.py" to test “construct_single_network.py”.
